project:
  type: website
  output-dir: docs

website:
  title: "Efua Ainooson Noonoo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: portfolio.qmd
        text: Portfolio
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© 2024 Efua Ainooson"
    right: "Powered by Quarto"

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
