project:
  type: website
  output-dir: docs


website:
  title: "Efua Ainooson's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    
    
  